2025-07-22 01:51:59,346 - root - INFO - Starting data ingestion process...
2025-07-22 01:52:00,718 - root - INFO - Train set shape: (8844, 32), Test set shape: (2211, 32)
2025-07-22 01:52:00,718 - root - ERROR - Error occurred during data ingestion: Error occurred in file D:\My folder 2025\python for data science\projects\NetworkSecurity\networksecurity\components\data_ingestion.py at line 70: Error occurred in file D:\My folder 2025\python for data science\projects\NetworkSecurity\networksecurity\components\data_ingestion.py at line 55: 'DataIngetionConfig' object has no attribute 'train_file_path'
